Format file

diff --git a/rootfs/etc/services.d/autovideoconverter/run b/rootfs/etc/services.d/autovideoconverter/run
--- a/rootfs/etc/services.d/autovideoconverter/run
+++ b/rootfs/etc/services.d/autovideoconverter/run
@@ -3,7 +3,7 @@
 # Prevent the error below from happening when comchap passes this param: --ffmpeg=/usr/local/bin/ffmpeg
 # /usr/local/bin/ffmpeg: error while loading shared libraries: libavdevice.so.58...
 if ! grep -q "/usr/local/lib" /etc/ld.so.conf; then
-    echo "/usr/local/lib" >> /etc/ld.so.conf
+    echo "/usr/local/lib" >>/etc/ld.so.conf
     ldconfig
 fi
 
@@ -70,13 +70,13 @@ WATCHDIR_HASH_isset() {
 WATCHDIR_HASH_update() {
     WATCHDIR="$1"
     mkdir -p "$WATCHDIR_HASH/$WATCHDIR"
-    WATCHDIR_HASH_calculate "$WATCHDIR" > "$WATCHDIR_HASH/$WATCHDIR/hash"
+    WATCHDIR_HASH_calculate "$WATCHDIR" >"$WATCHDIR_HASH/$WATCHDIR/hash"
 }
 
 WATCHDIR_HASH_changed() {
     WATCHDIR="$1"
-    [ ! -f "$WATCHDIR_HASH/$WATCHDIR/hash" ] || \
-    [ "$(cat "$WATCHDIR_HASH/$WATCHDIR/hash")" != "$(WATCHDIR_HASH_calculate "$WATCHDIR")" ]
+    [ ! -f "$WATCHDIR_HASH/$WATCHDIR/hash" ] ||
+        [ "$(cat "$WATCHDIR_HASH/$WATCHDIR/hash")" != "$(WATCHDIR_HASH_calculate "$WATCHDIR")" ]
 }
 
 get_video_hash() {
@@ -96,8 +96,8 @@ get_video_titles() {
 process_video() {
     video="$1"
     wf="$2"
-	date=$(date +"%d-%m-%Y-%H%M")
-	
+    date=$(date +"%d-%m-%Y-%H%M")
+
     # Skip video if it doesn't exists (may have been removed while processing
     # the watch directory).
     if [ ! -f "$video" ] && [ ! -d "$video" ]; then
@@ -141,178 +141,174 @@ process_video() {
 
     # Set the output directory.
     case "$AC_OUTPUT_SUBDIR" in
-        UNSET)
-            OUTPUT_DIR="$AC_OUTPUT_DIR"
-            ;;
-        SAME_AS_SRC)
-            dirname="$(dirname "$video" | sed "s|^$wf||")"
-            OUTPUT_DIR="$AC_OUTPUT_DIR/$dirname"
-            ;;
-        *)
-            OUTPUT_DIR="$AC_OUTPUT_DIR/$AC_OUTPUT_SUBDIR"
-            ;;
+    UNSET)
+        OUTPUT_DIR="$AC_OUTPUT_DIR"
+        ;;
+    SAME_AS_SRC)
+        dirname="$(dirname "$video" | sed "s|^$wf||")"
+        OUTPUT_DIR="$AC_OUTPUT_DIR/$dirname"
+        ;;
+    *)
+        OUTPUT_DIR="$AC_OUTPUT_DIR/$AC_OUTPUT_SUBDIR"
+        ;;
     esac
     OUTPUT_DIR="$(echo "$OUTPUT_DIR" | sed 's|/\+|/|g' | sed 's|/\+$||')"
 
+    log "=======================================     CONVERSION START     ================================================="
+    log " "
+    log "Starting conversion of '$video'..."
+    #log "$NUM_VIDEO_TITLES title(s) to process."
 
-	log "=======================================     CONVERSION START     ================================================="
-	log " "
-	log "Starting conversion of '$video'..."
-	#log "$NUM_VIDEO_TITLES title(s) to process."
-    
-	hb_rc=0
+    hb_rc=0
     comskip_rc=0
-	cc_rc=0
+    cc_rc=0
 
     # Get the output file basename: start with the one of the input file.
-	basename="$(basename "$video" | sed 's/\.[^.]*$//')"
+    basename="$(basename "$video" | sed 's/\.[^.]*$//')"
 
+    # Now set the final output filename by adding the extension.
+    OUTPUT_FILE="$OUTPUT_DIR/$basename.$AC_FORMAT"
+    OUTPUT_EDL="$OUTPUT_DIR/$basename.edl"
+    OUTPUT_SRT="$OUTPUT_DIR/$basename.srt"
 
-	# Now set the final output filename by adding the extension.
-	OUTPUT_FILE="$OUTPUT_DIR/$basename.$AC_FORMAT"
-	OUTPUT_EDL="$OUTPUT_DIR/$basename.edl"
-	OUTPUT_SRT="$OUTPUT_DIR/$basename.srt"
+    # Call pre conversion hook.
+    if [ -f /config/hooks/pre_conversion.sh ]; then
+        log "Executing pre-conversion hook..."
+        /usr/bin/with-contenv sh /config/hooks/pre_conversion.sh "$OUTPUT_FILE" "$video"
+        log "Pre-conversion hook exited with $?"
+    fi
 
-	# Call pre conversion hook.
-	if [ -f /config/hooks/pre_conversion.sh ]; then
-		log "Executing pre-conversion hook..."
-		/usr/bin/with-contenv sh /config/hooks/pre_conversion.sh "$OUTPUT_FILE" "$video" 
-		log "Pre-conversion hook exited with $?"
-	fi
+    # Skip video if it doesn't exists (may have been removed by the
+    # pre-conversion hook).
+    if [ ! -f "$video" ] && [ ! -d "$video" ]; then
+        log "Skipping '$video': no longer exists."
+        hb_rc=1
+    fi
 
-	# Skip video if it doesn't exists (may have been removed by the
-	# pre-conversion hook).
-	if [ ! -f "$video" ] && [ ! -d "$video" ]; then
-		log "Skipping '$video': no longer exists."
-		hb_rc=1
-	fi
+    # Check whether destination already exists
+    if [ -f "$OUTPUT_FILE" ]; then
+        hb_rc=1
+        log "ERROR: Destination file '$OUTPUT_FILE' already exists."
+    fi
 
-	# Check whether destination already exists
-	if [ -f "$OUTPUT_FILE" ]; then
-		hb_rc=1
-		log "ERROR: Destination file '$OUTPUT_FILE' already exists."
-	fi
+    # Set the temporary output directory: this is where the video will be
+    # actually written before being moved its final location once conversion is
+    # terminated.
+    OUTPUT_DIR_TMP="$(mktemp -d "$OUTPUT_DIR/.XXXXXX")"
+    if [ ! -d "$OUTPUT_DIR_TMP" ]; then
+        hb_rc=1
+        log "ERROR: Failed to create temporary directory under '$AC_OUTPUT_DIR'."
+    fi
 
-	# Set the temporary output directory: this is where the video will be
-	# actually written before being moved its final location once conversion is
-	# terminated.
-	OUTPUT_DIR_TMP="$(mktemp -d "$OUTPUT_DIR/.XXXXXX")"
-	if [ ! -d "$OUTPUT_DIR_TMP" ]; then
-		hb_rc=1
-		log "ERROR: Failed to create temporary directory under '$AC_OUTPUT_DIR'."
-	fi
-	
-	# Set the temporary output filename.
-	OUTPUT_FILE_TMP="$OUTPUT_DIR_TMP/$basename.$AC_FORMAT"
-	OUTPUT_EDL_TMP="$OUTPUT_DIR_TMP/$basename.edl"
-	OUTPUT_SRT_TMP="$OUTPUT_DIR_TMP/$basename.srt"
-	INPUT="$video"
-	log "-------------------------------------"
-	
-	# Execute Comcut
-	if [ $hb_rc -eq 0 ] && [ "$AC_POST_PROC" = comcut ]; then
-		log "COMCUT START"
-		log "COPY FILE TO TEMP DIRECTORY"
-			cp "$INPUT" "$OUTPUT_DIR_TMP/$basename.$AC_SOURCE_EXT"
-			INPUT="$OUTPUT_DIR_TMP/$basename.$AC_SOURCE_EXT"
-            # Comcut doesn't support using comskip hw accel
-            /opt/comskip/comskip --comskip-ini=/config/comskip/comskip.ini "$INPUT" "$COMSKIP_FLAGS" 1>> /config/log/comskip/"$basename"."$date".log 2>&1
-			/opt/comchap/comcut --lockfile="$OUTPUT_DIR/$basename.lock" 1>> /config/log/comskip/"$basename"."$date".log 2>&1
-			comskip_rc=$?
-		log "COMCUT FINISH WITH STATUS $?"
-		log "-------------------------------------"
-	fi
-	
-	# Execute Ccextractor
-	if [ $hb_rc -eq 0 ] && [ "$AC_SUBTITLE" = 0 ]; then
-		log "CCEXTRACTOR START"
-			ccextractor "$INPUT" -o "$OUTPUT_SRT_TMP" 1>> /config/log/ccextractor/"$basename"."$date".log 2>&1
-			cc_rc=$?
-		log "CCEXTRATOR FINISH WITH STATUS $cc_rc"
-		log "-------------------------------------"
-	fi
-	
-	# Invoke FFMPEG.
-	if [ $hb_rc -eq 0 ]; then
-		
-		log "FFMPEG START"
-		echo "------- CONVERSION OUTPUT $(date) -------" >> \
-			/config/log/conversion.log
-		$FFMPEG_CLI "$INPUT" "$OUTPUT_FILE_TMP" "$OUTPUT_SRT_TMP" 2>> \
-			/config/log/conversion.log | \
-			/usr/bin/unbuffer -p grep "^Encoding" | \
-			stdbuf -oL cut -d',' -f2- | \
-			tee >(log_hb_encode_progress) > /dev/null
-		hb_rc=$?
-		log "FFMPEG FINISH WITH STATUS $hb_rc"
-		log "-------------------------------------"
-		
-		
-		# Make sure the output file has been generated.
-		if [ $hb_rc -eq 0 ] && [ ! -f "$OUTPUT_FILE_TMP" ]; then
-			hb_rc=1
-		fi
-		
-		# Execute Comchap
-		if [ $hb_rc -eq 0 ] && [ "$AC_POST_PROC" = comchap ]; then
-		log "COMCHAP START"
-			/opt/comchap/comchap --lockfile="$OUTPUT_DIR_TMP/$basename.lock" --ffmpeg=/usr/local/bin/ffmpeg --keep-edl --comskip=/opt/Comskip/comskip --comskip-ini=/config/comskip/comskip.ini "$OUTPUT_FILE_TMP" 1>> /config/log/comskip/"$basename"."$date".log 2>&1
-			comskip_rc=$?
-		log "COMCHAP FINISH WITH STATUS $comskip_rc"
-		log "-------------------------------------"
-		fi
-				
-		# Move the file to its final location if conversion terminated
-		# successfully.
-		if [ $hb_rc -eq 0 ] && [ -f "$OUTPUT_FILE_TMP" ]; then
-			mkdir -p "$OUTPUT_DIR"
-			log "MOVE TMP FILE TO DESTINATION FOLDER"
-			mv "$OUTPUT_FILE_TMP" "$OUTPUT_FILE" 
-		fi
-		
-		if [ $comskip_rc -eq 0 ] && [ -f "$OUTPUT_EDL_TMP" ]; then
-			log "MOVE EDL FILE TO DESTINATION FOLDER"
-			mv "$OUTPUT_EDL_TMP" "$OUTPUT_EDL" 
-		fi
-		
-		if [ $cc_rc -eq 0 ] && [ -f "$OUTPUT_SRT_TMP" ]; then
-			log "MOVE SRT FILE TO DESTINATION FOLDER"
-			mv "$OUTPUT_SRT_TMP" "$OUTPUT_SRT" 
-		fi
+    # Set the temporary output filename.
+    OUTPUT_FILE_TMP="$OUTPUT_DIR_TMP/$basename.$AC_FORMAT"
+    OUTPUT_EDL_TMP="$OUTPUT_DIR_TMP/$basename.edl"
+    OUTPUT_SRT_TMP="$OUTPUT_DIR_TMP/$basename.srt"
+    INPUT="$video"
+    log "-------------------------------------"
 
-		if [ ! -f "$OUTPUT_EDL" ]; then
-			log "Comskip failed."
-			echo "$video $hash" >> "$FAILED_COMSKIP"
-		fi
+    # Execute Comcut
+    if [ $hb_rc -eq 0 ] && [ "$AC_POST_PROC" = comcut ]; then
+        log "COMCUT START"
+        log "COPY FILE TO TEMP DIRECTORY"
+        cp "$INPUT" "$OUTPUT_DIR_TMP/$basename.$AC_SOURCE_EXT"
+        INPUT="$OUTPUT_DIR_TMP/$basename.$AC_SOURCE_EXT"
+        # Comcut doesn't support using comskip hw accel
+        /opt/comskip/comskip --comskip-ini=/config/comskip/comskip.ini "$INPUT" "$COMSKIP_FLAGS" 1>>/config/log/comskip/"$basename"."$date".log 2>&1
+        /opt/comchap/comcut --lockfile="$OUTPUT_DIR/$basename.lock" 1>>/config/log/comskip/"$basename"."$date".log 2>&1
+        comskip_rc=$?
+        log "COMCUT FINISH WITH STATUS $?"
+        log "-------------------------------------"
+    fi
 
-		if [ ! -f "$OUTPUT_SRT" ]; then
-			log "CCextrator failed."
-			echo "$video $hash" >> "$FAILED_CCEXTRACTOR"
-		fi
-		
-	fi	
-	
-		# Remove tmp directory
-		log "-------------------------------------"
-		rm -rf "$OUTPUT_DIR_TMP"
-		log "TMP DIRECTORY REMOVED"
-		
-		# Call post conversion hook.
-		if [ -f /config/hooks/post_conversion.sh ]; then
-			log "Executing post-conversion hook..."
-			/usr/bin/with-contenv sh /config/hooks/post_conversion.sh $hb_rc "$OUTPUT_FILE" "$video" 
-			log "Post-conversion hook exited with $?"
-		fi
-		
-	log " "
-	log "=======================================     CONVERSION DONE     ================================================="
-		
-	
-	if [ $hb_rc -eq 0 ]; then
+    # Execute Ccextractor
+    if [ $hb_rc -eq 0 ] && [ "$AC_SUBTITLE" = 0 ]; then
+        log "CCEXTRACTOR START"
+        ccextractor "$INPUT" -o "$OUTPUT_SRT_TMP" 1>>/config/log/ccextractor/"$basename"."$date".log 2>&1
+        cc_rc=$?
+        log "CCEXTRATOR FINISH WITH STATUS $cc_rc"
+        log "-------------------------------------"
+    fi
+
+    # Invoke FFMPEG.
+    if [ $hb_rc -eq 0 ]; then
+
+        log "FFMPEG START"
+        echo "------- CONVERSION OUTPUT $(date) -------" >> \
+            /config/log/conversion.log
+        $FFMPEG_CLI "$INPUT" "$OUTPUT_FILE_TMP" "$OUTPUT_SRT_TMP" 2>> \
+            /config/log/conversion.log |
+            /usr/bin/unbuffer -p grep "^Encoding" |
+            stdbuf -oL cut -d',' -f2- |
+            tee >(log_hb_encode_progress) >/dev/null
+        hb_rc=$?
+        log "FFMPEG FINISH WITH STATUS $hb_rc"
+        log "-------------------------------------"
+
+        # Make sure the output file has been generated.
+        if [ $hb_rc -eq 0 ] && [ ! -f "$OUTPUT_FILE_TMP" ]; then
+            hb_rc=1
+        fi
+
+        # Execute Comchap
+        if [ $hb_rc -eq 0 ] && [ "$AC_POST_PROC" = comchap ]; then
+            log "COMCHAP START"
+            /opt/comchap/comchap --lockfile="$OUTPUT_DIR_TMP/$basename.lock" --ffmpeg=/usr/local/bin/ffmpeg --keep-edl --comskip=/opt/Comskip/comskip --comskip-ini=/config/comskip/comskip.ini "$OUTPUT_FILE_TMP" 1>>/config/log/comskip/"$basename"."$date".log 2>&1
+            comskip_rc=$?
+            log "COMCHAP FINISH WITH STATUS $comskip_rc"
+            log "-------------------------------------"
+        fi
+
+        # Move the file to its final location if conversion terminated
+        # successfully.
+        if [ $hb_rc -eq 0 ] && [ -f "$OUTPUT_FILE_TMP" ]; then
+            mkdir -p "$OUTPUT_DIR"
+            log "MOVE TMP FILE TO DESTINATION FOLDER"
+            mv "$OUTPUT_FILE_TMP" "$OUTPUT_FILE"
+        fi
+
+        if [ $comskip_rc -eq 0 ] && [ -f "$OUTPUT_EDL_TMP" ]; then
+            log "MOVE EDL FILE TO DESTINATION FOLDER"
+            mv "$OUTPUT_EDL_TMP" "$OUTPUT_EDL"
+        fi
+
+        if [ $cc_rc -eq 0 ] && [ -f "$OUTPUT_SRT_TMP" ]; then
+            log "MOVE SRT FILE TO DESTINATION FOLDER"
+            mv "$OUTPUT_SRT_TMP" "$OUTPUT_SRT"
+        fi
+
+        if [ ! -f "$OUTPUT_EDL" ]; then
+            log "Comskip failed."
+            echo "$video $hash" >>"$FAILED_COMSKIP"
+        fi
+
+        if [ ! -f "$OUTPUT_SRT" ]; then
+            log "CCextrator failed."
+            echo "$video $hash" >>"$FAILED_CCEXTRACTOR"
+        fi
+
+    fi
+
+    # Remove tmp directory
+    log "-------------------------------------"
+    rm -rf "$OUTPUT_DIR_TMP"
+    log "TMP DIRECTORY REMOVED"
+
+    # Call post conversion hook.
+    if [ -f /config/hooks/post_conversion.sh ]; then
+        log "Executing post-conversion hook..."
+        /usr/bin/with-contenv sh /config/hooks/post_conversion.sh $hb_rc "$OUTPUT_FILE" "$video"
+        log "Post-conversion hook exited with $?"
+    fi
+
+    log " "
+    log "=======================================     CONVERSION DONE     ================================================="
+
+    if [ $hb_rc -eq 0 ]; then
         log "Conversion ended successfully."
-		echo "$video $hash" >> "$SUCCESSFUL_CONVERSIONS"
-        
-		if [ "$AC_KEEP_SOURCE" -eq 0 ]; then
+        echo "$video $hash" >>"$SUCCESSFUL_CONVERSIONS"
+
+        if [ "$AC_KEEP_SOURCE" -eq 0 ]; then
             rm -r "$video"
             log "Removed $video'."
             # Remove directory if empty (hidden files/folders are ignored).
@@ -323,17 +319,17 @@ process_video() {
                 videodir="$(dirname "$videodir")"
             done
         fi
-		
-		if [ "$AC_KEEP_SOURCE" -eq 2 ];  then
-			mv "$video" "$AC_BACKUP_DIR/$basename.$AC_SOURCE_EXT"
-			log "backuped $video'."
-		fi
-		
+
+        if [ "$AC_KEEP_SOURCE" -eq 2 ]; then
+            mv "$video" "$AC_BACKUP_DIR/$basename.$AC_SOURCE_EXT"
+            log "backuped $video'."
+        fi
+
     else
         log "Conversion failed."
-        echo "$video $hash" >> "$FAILED_CONVERSIONS"
+        echo "$video $hash" >>"$FAILED_CONVERSIONS"
     fi
-	log "========================================================================================================="
+    log "========================================================================================================="
 }
 
 process_watch_folder() {
@@ -354,14 +350,13 @@ process_watch_folder() {
     WATCHDIR_HASH_update "$WF"
     log "Processing watch folder '$WF'..."
     FILELIST="$(mktemp)"
-    find "$WF" -follow -type f -not -path '*/\.*' -printf "%T@ %p\n" | \
-        sort -n | \
-        cut -d' ' -f2- | \
-        sed 's|/VIDEO_TS/.*$|/VIDEO_TS|g' | \
-        sed 's|/BDMV/.*$|/BDMV|g' | \
-        uniq > "$FILELIST"
-    while read -u 3 FILE
-    do
+    find "$WF" -follow -type f -not -path '*/\.*' -printf "%T@ %p\n" |
+        sort -n |
+        cut -d' ' -f2- |
+        sed 's|/VIDEO_TS/.*$|/VIDEO_TS|g' |
+        sed 's|/BDMV/.*$|/BDMV|g' |
+        uniq >"$FILELIST"
+    while read -u 3 FILE; do
         process_video "$FILE" "$WF"
     done 3<"$FILELIST"
     rm "$FILELIST"
@@ -404,8 +399,7 @@ while true; do
 
         # Apply per-watch folder settings.
         if [ -n "${DIR#*/watch}" ]; then
-            for VAR in FORMAT SOURCE_STABLE_TIME SOURCE_MIN_DURATION OUTPUT_DIR OUTPUT_SUBDIR KEEP_SOURCE SOURCE_EXT POST_PROC SUBTITLE
-            do
+            for VAR in FORMAT SOURCE_STABLE_TIME SOURCE_MIN_DURATION OUTPUT_DIR OUTPUT_SUBDIR KEEP_SOURCE SOURCE_EXT POST_PROC SUBTITLE; do
                 eval "AC_$VAR=\"\${AUTOMATED_CONVERSION_${VAR}_${DIR#*/watch}:-\$AC_$VAR}\""
             done
         fi
